package com.lifeos.ai.grounding;

import com.lifeos.ai.dto.AssistantCitationDto;
import com.lifeos.rag.retrieval.dto.RetrievalCitationDto;
import com.lifeos.rag.retrieval.dto.RetrievedChunkDto;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Validates inline LLM citations against authorized Phase 12 sources,
 * filtering hallucinated references and producing verified provenance DTOs.
 */
@Slf4j
@Component
public class CitationValidator {

    private static final Pattern CITATION_PATTERN = Pattern.compile("\\[(\\d+)\\]");

    /**
     * Validates and sanitizes LLM-generated text against assembled context.
     *
     * @param rawAnswer        raw text generated by the LLM
     * @param assembledContext context containing valid 1-indexed source maps
     * @return validated citations and sanitized answer text with hallucinations stripped
     */
    public ValidatedCitationResult validate(String rawAnswer, AssembledContext assembledContext) {
        if (rawAnswer == null || rawAnswer.isBlank()) {
            return ValidatedCitationResult.builder()
                    .sanitizedContent("")
                    .validCitations(List.of())
                    .invalidCitationsRemoved(0)
                    .build();
        }

        if (assembledContext == null || assembledContext.getSourceCount() == 0) {
            // Strip any citations if no sources were supplied
            String cleaned = CITATION_PATTERN.matcher(rawAnswer).replaceAll("").trim();
            return ValidatedCitationResult.builder()
                    .sanitizedContent(cleaned)
                    .validCitations(List.of())
                    .invalidCitationsRemoved(0)
                    .build();
        }

        Matcher matcher = CITATION_PATTERN.matcher(rawAnswer);
        Set<Integer> validIndicesFound = new LinkedHashSet<>();
        Set<Integer> invalidIndicesFound = new HashSet<>();

        while (matcher.find()) {
            try {
                int index = Integer.parseInt(matcher.group(1));
                if (assembledContext.getCitationMap().containsKey(index)
                        || assembledContext.getSourceMap().containsKey(index)) {
                    validIndicesFound.add(index);
                } else {
                    invalidIndicesFound.add(index);
                }
            } catch (NumberFormatException ignored) {
            }
        }

        String sanitizedText = rawAnswer;
        for (Integer invalidIdx : invalidIndicesFound) {
            log.warn("Detected hallucinated citation index [{}]. Stripping from response.", invalidIdx);
            sanitizedText = sanitizedText.replace("[" + invalidIdx + "]", "");
        }

        List<AssistantCitationDto> validCitations = new ArrayList<>();
        for (Integer idx : validIndicesFound) {
            RetrievalCitationDto cit = assembledContext.getCitationMap().get(idx);
            RetrievedChunkDto chunk = assembledContext.getSourceMap().get(idx);

            if (cit != null) {
                validCitations.add(AssistantCitationDto.builder()
                        .citationIndex(idx)
                        .documentId(cit.getDocumentId())
                        .documentTitle(cit.getDocumentTitle())
                        .documentVersion(cit.getDocumentVersion())
                        .chunkId(cit.getChunkId())
                        .pageNumber(cit.getPageNumber())
                        .sectionTitle(cit.getSectionTitle())
                        .snippet(chunk != null ? chunk.getSnippet() : "")
                        .sourceCitation(cit.getSourceCitation())
                        .relevanceScore(cit.getRelevanceScore())
                        .build());
            } else if (chunk != null) {
                validCitations.add(AssistantCitationDto.builder()
                        .citationIndex(idx)
                        .documentId(chunk.getDocumentId())
                        .documentTitle(chunk.getDocumentTitle())
                        .documentVersion(chunk.getDocumentVersion())
                        .chunkId(chunk.getChunkId())
                        .pageNumber(chunk.getPageNumber())
                        .sectionTitle(chunk.getSectionTitle())
                        .snippet(chunk.getSnippet())
                        .sourceCitation("[" + chunk.getDocumentTitle() + ", Page " + chunk.getPageNumber() + "]")
                        .relevanceScore(chunk.getRelevanceScore())
                        .build());
            }
        }

        return ValidatedCitationResult.builder()
                .sanitizedContent(sanitizedText.replaceAll("\\s{2,}", " ").trim())
                .validCitations(validCitations)
                .invalidCitationsRemoved(invalidIndicesFound.size())
                .build();
    }
}
