package com.lifeos.document.entity;

public enum DocumentType {
    ID_PROOF,
    POLICY,
    INVOICE,
    RECEIPT,
    STATEMENT,
    PRESCRIPTION,
    LAB_REPORT,
    CONSULTATION_SUMMARY,
    DISCHARGE_SUMMARY,
    DIAGNOSTIC_REPORT,
    VACCINATION_RECORD,
    MEDICAL_BILL,
    TICKET,
    BOARDING_PASS,
    HOTEL_CONFIRMATION,
    ITINERARY,
    TRAVEL_INSURANCE,
    VISA,
    CONTRACT,
    TAX_RETURN,
    WARRANTY_CERTIFICATE,
    USER_MANUAL,
    OTHER
}
