package com.lifeos.audit.entity;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_TOKEN_REFRESH,
    AUTH_LOGOUT,
    USER_PROFILE_UPDATE,
    USER_PASSWORD_CHANGE,
    ACTION_HITL_CONFIRMED,
    ACTION_HITL_REJECTED,
    DATA_EXPORT_REQUESTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    POLICY_COMPARISON_EXECUTED
}
